# Be sure to restart your server when you modify this file.

# Your ***REMOVED*** key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the ***REMOVED*** is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake ***REMOVED***` to generate a secure ***REMOVED*** key.

# Make sure the ***REMOVED***s in this file are kept private
# if you're sharing your code publicly.

development:
  ***REMOVED***_key_base: ***REMOVED***

test:
  ***REMOVED***_key_base: ***REMOVED***

# Do not keep production ***REMOVED***s in the repository,
# instead read values from the environment.
production:
  ***REMOVED***_key_base: <%= ENV["SECRET_KEY_BASE"] %>
